import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/AntdRegistry/AntdRegistry";
import Header from "@/components/layouts/header/header";
import Footer from "@/components/layouts/footer/footer";
import { ConfigProvider, Layout } from "antd";
import DashboardLayout from "@/components/layouts/dashboard-layout/dashboard_layout";
import theme from "@/theme/theme.config";
import { SidebarProvider } from "@/providers/SidebarProvider";
import { CartProvider } from "@/providers/CartProvider";
import { KitchenProvider } from "@/providers/KitchenProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ConfigProvider theme={theme}>
            <SidebarProvider>
              <KitchenProvider>
                <CartProvider>
                  <DashboardLayout>{children}</DashboardLayout>
                </CartProvider>
              </KitchenProvider>
            </SidebarProvider>
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
